# GitHub Pages Configuration
# This file helps with GitHub Pages deployment

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Site settings
title: "PromptVCS - Prompt Version Control System"
description: "A Git-like version control system for AI prompts and prompt engineering teams"
url: "https://username.github.io" # Replace with your GitHub Pages URL
baseurl: "/promptvcs" # Replace with your repository name

# Exclude files from Jekyll build
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Include files
include:
  - _headers

# Custom settings
markdown: kramdown
highlighter: rouge
